" 
" vimrc
" 
" Author: Juan Manuel Rey <juanmanuel.reyportal@gmail.com>
"    URL: http://blog.jreypo.io
"

" General configuration

set nocompatible

" Theme and colors configuration

set t_Co=256
syntax on
colorscheme github
set background=light

" Vim interface

set number
set ruler
set visualbell
set statusline=%<%f\%h%m%r%=%-20.(line=%l\ \ col=%c%V\ \ totlin=%L%)\ \ \%h%m%r%=%-40(bytval=0x%B,%n%Y%)\%P
set ignorecase
set nohlsearch
set laststatus=2
set helplang=en
set langmenu=none

" Format text 

set mouse=a
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set nowrap
set autoindent

