colorscheme github
syntax enable
set tabstop=4
set softtabstop=4
set expandtab
set number
set showcmd
set nowrap
set cursorline
filetype indent on
set wildmenu
set lazyredraw
" Search settings
set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR>
" Folding settings
set foldenable
set foldlevelstart=10
set foldnestmax=10
nnoremap <space> za
set foldmethod=indent
" File navigatin settings
nnoremap j gj
nnoremap k gk
nnoremap C-e ^
nnoremap C-a $
nnoremap gV `[v`]

