# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# My customized alias	

-='cd -'
..='cd ..'
...='cd ../..'
alias ls='ls -aF --color=auto'
alias ll='ls -ls'
alias l='ls -lsh'
alias bdf='df -h'
alias grep='grep --color'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias mkdir='mkdir -pv'
alias pcpu='ps auxf | sort -nr -k 3 | head -10'
alias pmem='ps auxf | sort -nr -k 4 | head -10'
alias ports='netstat -tulanp'
alias path='echo -e ${PATH//:/\\n}'
alias h='history'
alias j='jobs -l'
alias cls=clear

# Git alias, extracted from Bash-IT and Oh My ZSH aliases files

GIT=`which git`

if [ -e $GIT ]
	then
	alias gs='git status'
	alias gci='git commit --interactive'
	alias gcl='git clone'
	alias gcm='git commit -v -m'
	alias gco='git checkout'
	alias gl='git pull'
	alias gm='git merge'
	alias gp='git push'
	alias gpo='git push origin'
	alias gpp='git pull && git push'
	alias gpr='git pull --rebase'
fi